// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404124609_AddGoalSettings")]
    partial class AddGoalSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.ActiveWorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ActiveWorkoutSessions");
                });

            modelBuilder.Entity("backend.Models.ActiveWorkoutSessionExerciseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveWorkoutSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveWorkoutSessionId");

                    b.ToTable("ActiveWorkoutSessionExerciseEntries");
                });

            modelBuilder.Entity("backend.Models.ActiveWorkoutSessionExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveWorkoutSessionExerciseEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ActiveWorkoutSessionExerciseEntryId");

                    b.ToTable("ActiveWorkoutSessionExerciseSets");
                });

            modelBuilder.Entity("backend.Models.ExerciseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseEntries");
                });

            modelBuilder.Entity("backend.Models.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseEntryId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("backend.Models.GoalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FitnessPhase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TargetBodyWeightKg")
                        .HasColumnType("numeric");

                    b.Property<int?>("WeeklyWorkoutTarget")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GoalSettings");
                });

            modelBuilder.Entity("backend.Models.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("backend.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("backend.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("backend.Models.WorkoutTemplateExerciseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutTemplateExerciseEntries");
                });

            modelBuilder.Entity("backend.Models.WorkoutTemplateExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.Property<int>("WorkoutTemplateExerciseEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateExerciseEntryId");

                    b.ToTable("WorkoutTemplateExerciseSets");
                });

            modelBuilder.Entity("backend.Models.ActiveWorkoutSessionExerciseEntry", b =>
                {
                    b.HasOne("backend.Models.ActiveWorkoutSession", "ActiveWorkoutSession")
                        .WithMany("ExerciseEntries")
                        .HasForeignKey("ActiveWorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveWorkoutSession");
                });

            modelBuilder.Entity("backend.Models.ActiveWorkoutSessionExerciseSet", b =>
                {
                    b.HasOne("backend.Models.ActiveWorkoutSessionExerciseEntry", "ActiveWorkoutSessionExerciseEntry")
                        .WithMany("Sets")
                        .HasForeignKey("ActiveWorkoutSessionExerciseEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveWorkoutSessionExerciseEntry");
                });

            modelBuilder.Entity("backend.Models.ExerciseEntry", b =>
                {
                    b.HasOne("backend.Models.Workout", "Workout")
                        .WithMany("ExerciseEntries")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("backend.Models.ExerciseSet", b =>
                {
                    b.HasOne("backend.Models.ExerciseEntry", "ExerciseEntry")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseEntry");
                });

            modelBuilder.Entity("backend.Models.WorkoutTemplateExerciseEntry", b =>
                {
                    b.HasOne("backend.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("ExerciseEntries")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("backend.Models.WorkoutTemplateExerciseSet", b =>
                {
                    b.HasOne("backend.Models.WorkoutTemplateExerciseEntry", "WorkoutTemplateExerciseEntry")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutTemplateExerciseEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplateExerciseEntry");
                });

            modelBuilder.Entity("backend.Models.ActiveWorkoutSession", b =>
                {
                    b.Navigation("ExerciseEntries");
                });

            modelBuilder.Entity("backend.Models.ActiveWorkoutSessionExerciseEntry", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("backend.Models.ExerciseEntry", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("backend.Models.Workout", b =>
                {
                    b.Navigation("ExerciseEntries");
                });

            modelBuilder.Entity("backend.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("ExerciseEntries");
                });

            modelBuilder.Entity("backend.Models.WorkoutTemplateExerciseEntry", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
